Repository hmcts/probate-persistence-service, pull requests merged in 2019-02, with the labels that each got.

#84 Pro 3554 merge v2
  Jenkinsfile_old_tactical
  build.gradle
  infrastructure/main.tf
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  src/functionalTest/java/uk/gov/hmcts/probate/functional/test/PersistenceServiceRegistrySequenceControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/probate/functional/test/PersistenceServiceSequenceNumberControllerTests.java
  src/libs/AI-Agent.xml
  src/main/java/uk/gov/hmcts/probate/services/persistence/ApplicationConfig.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/component/RegistryUpdate.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/RegistrySequenceController.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberController.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/model/Registry.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/repository/RegistryRepository.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/services/RegistrySequenceService.java
  src/main/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberService.java
  src/main/resources/application.yml
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/test/java/uk/gov/hmcts/probate/services/persistence/RegistryInApplicationConfigTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/TestUtils.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/RegistrySequenceControllerTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberControllerTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/model/RegistryTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/repository/FormDataRepositoryTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/repository/RegistryRepositoryTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/repository/RepositoryTestConfiguration.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepositoryTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/repository/TestApplicationContextInitializer.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/services/GitCommitInfoEndpointTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/services/RegistrySequenceServiceTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonBinarySqlTypeDescriptorTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonStringSqlTypeDescriptorTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonStringTypeTest.java
  src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonTypeDescriptorTest.java
  src/test/resources/application-registry.yml
  src/test/resources/registry.json
  src/test/resources/registryData.json
  src/test/resources/registryUpdated.json
Labels: ns:probate-persistence-service-pr-84

#85 Update Java version
  Dockerfile
  build.gradle
Labels: ns:probate-persistence-service-pr-85

#86 PRO-4733 update java
  Dockerfile
Labels: ns:probate-persistence-service-pr-86
